#!/bin/bash

[ -f $(dirname $0)/../libvirt-functions/libvirt-functions ] && . $(dirname $0)/../libvirt-functions/libvirt-functions || { echo "$(dirname $0)/../libvirt-functions/libvirt-functions not found" 1>&2; exit 1; }


guests="in appproxy support master1 master2 master3 infranode1 infranode2 node1 node2"

function main() {

    local snapshot_tag=$1

    [ -z "${snapshot_tag}" ] && { echo "a snapshot tag must be specified" 1>&2; exit 1; }

    # make sure all guests are down. If at least one is up, fail

    for i in ${guests}; do
        local state
        state=$(virsh domstate ${i}) || exit 1
        if [ "${state}" != "shut off" ]; then
           echo "'${i}' is not shut down, cannot snapshot environment" 1>&2
           exit 1
        fi
    done

    # list the qcow2 images

    for i in ${guests}; do
        local image_volume=/main-storage-pool/${i}.qcow2
        virsh vol-info ${image_volume} || { echo "failed to query ${image_volume}" 1>&2; exit 1; }
    done

    # get the snapshot tag
    # snapshot all qcow2 images
    
}

main $@




